
//This file should be called cbmc_main_surgical_policy.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_surgical_policy.c F_surgical_policy.c


#include "F_surgical_policy.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for surgical_policy
	enforcervars_surgical_policy_t enf_surgical_policy;
    inputs_surgical_policy_t inputs_surgical_policy;
    outputs_surgical_policy_t outputs_surgical_policy;

	//set values to known state
    surgical_policy_init_all_vars(&enf_surgical_policy, &inputs_surgical_policy, &outputs_surgical_policy);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_surgical_policy.Suction = nondet_surgical_policy_input_0();
	inputs_surgical_policy.Bipolar = nondet_surgical_policy_input_1();
	inputs_surgical_policy.Dissecting = nondet_surgical_policy_input_2();
	inputs_surgical_policy.Cusa = nondet_surgical_policy_input_3();
	inputs_surgical_policy.CONSEC_Suction = nondet_surgical_policy_input_4();
	inputs_surgical_policy.CONSEC_Bipolar = nondet_surgical_policy_input_5();
	inputs_surgical_policy.CONSEC_Dissecting = nondet_surgical_policy_input_6();
	inputs_surgical_policy.CONSEC_Cusa = nondet_surgical_policy_input_7();
	inputs_surgical_policy.CONSEC_OFF_Suction = nondet_surgical_policy_input_8();
	inputs_surgical_policy.CONSEC_OFF_Bipolar = nondet_surgical_policy_input_9();
	inputs_surgical_policy.CONSEC_OFF_Dissecting = nondet_surgical_policy_input_10();
	inputs_surgical_policy.CONSEC_OFF_Cusa = nondet_surgical_policy_input_11();
	inputs_surgical_policy.TOTAL_Suction = nondet_surgical_policy_input_12();
	inputs_surgical_policy.IN_COOLDOWN_Dissecting = nondet_surgical_policy_input_13();
	inputs_surgical_policy.Dissecting_Ever_Used = nondet_surgical_policy_input_14();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_surgical_policy._policy_p1_state = nondet_surgical_policy_enf_p1_state() % 1;
	
	
	enf_surgical_policy._policy_p2_dissecting_time_state = nondet_surgical_policy_enf_p2_dissecting_time_state() % 1;
	
	
	enf_surgical_policy._policy_p3_total_suction_state = nondet_surgical_policy_enf_p3_total_suction_state() % 1;
	
	enf_surgical_policy._policy_p4_cooldown_dissecting_state = nondet_surgical_policy_enf_p4_cooldown_dissecting_state() % 1;
	
	enf_surgical_policy._policy_p5_precedence_cusa_state = nondet_surgical_policy_enf_p5_precedence_cusa_state() % 1;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	surgical_policy_run_via_enforcer(&enf_surgical_policy, &inputs_surgical_policy, &outputs_surgical_policy);

}


void surgical_policy_run(inputs_surgical_policy_t *inputs, outputs_surgical_policy_t *outputs) {
    //randomise controller

     
}

