
//This file should be called F_surgical_policy.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum surgical_policy_policy_p1_states { 
	POLICY_STATE_surgical_policy_p1_s0,
	POLICY_STATE_surgical_policy_p1_violation 
};

enum surgical_policy_policy_p2_dissecting_time_states { 
	POLICY_STATE_surgical_policy_p2_dissecting_time_s0,
	POLICY_STATE_surgical_policy_p2_dissecting_time_violation 
};

enum surgical_policy_policy_p3_total_suction_states { 
	POLICY_STATE_surgical_policy_p3_total_suction_s0,
	POLICY_STATE_surgical_policy_p3_total_suction_violation 
};

enum surgical_policy_policy_p4_cooldown_dissecting_states { 
	POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0,
	POLICY_STATE_surgical_policy_p4_cooldown_dissecting_violation 
};

enum surgical_policy_policy_p5_precedence_cusa_states { 
	POLICY_STATE_surgical_policy_p5_precedence_cusa_s0,
	POLICY_STATE_surgical_policy_p5_precedence_cusa_violation 
};


//Inputs to the function surgical_policy
typedef struct {
	bool Suction;
	bool Bipolar;
	bool Dissecting;
	bool Cusa;
	uint32_t CONSEC_Suction;
	uint32_t CONSEC_Bipolar;
	uint32_t CONSEC_Dissecting;
	uint32_t CONSEC_Cusa;
	uint32_t CONSEC_OFF_Suction;
	uint32_t CONSEC_OFF_Bipolar;
	uint32_t CONSEC_OFF_Dissecting;
	uint32_t CONSEC_OFF_Cusa;
	uint32_t TOTAL_Suction;
	bool IN_COOLDOWN_Dissecting;
	bool Dissecting_Ever_Used;
	
} inputs_surgical_policy_t;

//Outputs from the function surgical_policy
typedef struct {
	
} outputs_surgical_policy_t;

//enforcer state and vars:
typedef struct {
	enum surgical_policy_policy_p1_states _policy_p1_state;
	//internal vars
	
	
	enum surgical_policy_policy_p2_dissecting_time_states _policy_p2_dissecting_time_state;
	//internal vars
	
	
	enum surgical_policy_policy_p3_total_suction_states _policy_p3_total_suction_state;
	//internal vars
	
	
	enum surgical_policy_policy_p4_cooldown_dissecting_states _policy_p4_cooldown_dissecting_state;
	//internal vars
	
	
	enum surgical_policy_policy_p5_precedence_cusa_states _policy_p5_precedence_cusa_state;
	//internal vars
	
	
	
} enforcervars_surgical_policy_t;

#define CONST_p2_dissecting_time_MAX_Dissecting 5
#define CONST_p3_total_suction_MAX_TOTAL_Suction 15


//This function is provided in "F_surgical_policy.c"
//It sets up the variable structures to their initial values
void surgical_policy_init_all_vars(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided in "F_surgical_policy.c"
//It will run the synthesised enforcer and call the controller function
void surgical_policy_run_via_enforcer(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided from the user
//It is the controller function
extern void surgical_policy_run(inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//enforcer functions


//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p1
void surgical_policy_run_input_enforcer_p1(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs);

//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p1
void surgical_policy_run_output_enforcer_p1(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided in "F_surgical_policy.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int surgical_policy_check_rv_status_p1(enforcervars_surgical_policy_t* me);


//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p2_dissecting_time
void surgical_policy_run_input_enforcer_p2_dissecting_time(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs);

//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p2_dissecting_time
void surgical_policy_run_output_enforcer_p2_dissecting_time(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided in "F_surgical_policy.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int surgical_policy_check_rv_status_p2_dissecting_time(enforcervars_surgical_policy_t* me);


//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p3_total_suction
void surgical_policy_run_input_enforcer_p3_total_suction(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs);

//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p3_total_suction
void surgical_policy_run_output_enforcer_p3_total_suction(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided in "F_surgical_policy.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int surgical_policy_check_rv_status_p3_total_suction(enforcervars_surgical_policy_t* me);


//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p4_cooldown_dissecting
void surgical_policy_run_input_enforcer_p4_cooldown_dissecting(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs);

//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p4_cooldown_dissecting
void surgical_policy_run_output_enforcer_p4_cooldown_dissecting(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided in "F_surgical_policy.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int surgical_policy_check_rv_status_p4_cooldown_dissecting(enforcervars_surgical_policy_t* me);


//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p5_precedence_cusa
void surgical_policy_run_input_enforcer_p5_precedence_cusa(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs);

//This function is provided in "F_surgical_policy.c"
//It will run the input enforcer for surgical_policy's policy p5_precedence_cusa
void surgical_policy_run_output_enforcer_p5_precedence_cusa(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs);

//This function is provided in "F_surgical_policy.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int surgical_policy_check_rv_status_p5_precedence_cusa(enforcervars_surgical_policy_t* me);


