
//This file should be called F_surgical_policy.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_surgical_policy.h"

void surgical_policy_init_all_vars(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_p1_state = POLICY_STATE_surgical_policy_p1_s0;
	//input policy internal vars
	
	
	me->_policy_p2_dissecting_time_state = POLICY_STATE_surgical_policy_p2_dissecting_time_s0;
	//input policy internal vars
	
	
	me->_policy_p3_total_suction_state = POLICY_STATE_surgical_policy_p3_total_suction_s0;
	//input policy internal vars
	
	
	me->_policy_p4_cooldown_dissecting_state = POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0;
	//input policy internal vars
	
	
	me->_policy_p5_precedence_cusa_state = POLICY_STATE_surgical_policy_p5_precedence_cusa_s0;
	//input policy internal vars
	
	
}

void surgical_policy_run_via_enforcer(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 surgical_policy_run_input_enforcer_p5_precedence_cusa(me, inputs);
	 surgical_policy_run_input_enforcer_p4_cooldown_dissecting(me, inputs);
	 surgical_policy_run_input_enforcer_p3_total_suction(me, inputs);
	 surgical_policy_run_input_enforcer_p2_dissecting_time(me, inputs);
	 surgical_policy_run_input_enforcer_p1(me, inputs);
	

	surgical_policy_run(inputs, outputs);

	//run policies in specified order for outputs
	surgical_policy_run_output_enforcer_p1(me, inputs,outputs);
	surgical_policy_run_output_enforcer_p2_dissecting_time(me, inputs,outputs);
	surgical_policy_run_output_enforcer_p3_total_suction(me, inputs,outputs);
	surgical_policy_run_output_enforcer_p4_cooldown_dissecting(me, inputs,outputs);
	surgical_policy_run_output_enforcer_p5_precedence_cusa(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY p1 BEGIN
//This will run the input enforcer for surgical_policy's policy p1
void surgical_policy_run_input_enforcer_p1(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs) {
	switch(me->_policy_p1_state) {
		case POLICY_STATE_surgical_policy_p1_s0:
			
			if(inputs->Suction && inputs->Bipolar) {
				//transition s0 -> violation on Suction and Bipolar
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				inputs->Bipolar = 0;
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p1 END

//INPUT POLICY p2_dissecting_time BEGIN
//This will run the input enforcer for surgical_policy's policy p2_dissecting_time
void surgical_policy_run_input_enforcer_p2_dissecting_time(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs) {
	switch(me->_policy_p2_dissecting_time_state) {
		case POLICY_STATE_surgical_policy_p2_dissecting_time_s0:
			
			if(inputs->Dissecting && inputs->CONSEC_Dissecting > CONST_p2_dissecting_time_MAX_Dissecting) {
				//transition s0 -> violation on Dissecting and CONSEC_Dissecting > MAX_Dissecting
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				inputs->Dissecting = 0;
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p2_dissecting_time END

//INPUT POLICY p3_total_suction BEGIN
//This will run the input enforcer for surgical_policy's policy p3_total_suction
void surgical_policy_run_input_enforcer_p3_total_suction(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs) {
	switch(me->_policy_p3_total_suction_state) {
		case POLICY_STATE_surgical_policy_p3_total_suction_s0:
			
			if(inputs->Suction && inputs->TOTAL_Suction > CONST_p3_total_suction_MAX_TOTAL_Suction) {
				//transition s0 -> violation on Suction and TOTAL_Suction > MAX_TOTAL_Suction
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				inputs->Suction = 0;
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p3_total_suction END

//INPUT POLICY p4_cooldown_dissecting BEGIN
//This will run the input enforcer for surgical_policy's policy p4_cooldown_dissecting
void surgical_policy_run_input_enforcer_p4_cooldown_dissecting(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs) {
	switch(me->_policy_p4_cooldown_dissecting_state) {
		case POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0:
			
			if(inputs->Dissecting && inputs->IN_COOLDOWN_Dissecting) {
				//transition s0 -> violation on Dissecting and IN_COOLDOWN_Dissecting
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				inputs->Dissecting = 0;
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p4_cooldown_dissecting END

//INPUT POLICY p5_precedence_cusa BEGIN
//This will run the input enforcer for surgical_policy's policy p5_precedence_cusa
void surgical_policy_run_input_enforcer_p5_precedence_cusa(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs) {
	switch(me->_policy_p5_precedence_cusa_state) {
		case POLICY_STATE_surgical_policy_p5_precedence_cusa_s0:
			
			if(inputs->Cusa && !(inputs->Dissecting_Ever_Used)) {
				//transition s0 -> violation on Cusa and not (Dissecting_Ever_Used)
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				inputs->Cusa = 0;
				
			} 
			
			break;

		
	}
}

//INPUT POLICY p5_precedence_cusa END



//output policies

//OUTPUT POLICY p1 BEGIN
//This will run the input enforcer for surgical_policy's policy p1
void surgical_policy_run_output_enforcer_p1(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p1_state) {
		case POLICY_STATE_surgical_policy_p1_s0:
			
			if(inputs->Suction && inputs->Bipolar) {
				//transition s0 -> violation on ( Suction and Bipolar )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p1_state) {
		case POLICY_STATE_surgical_policy_p1_s0:
			
			if( !(inputs->Suction && inputs->Bipolar)) {
				//transition s0 -> s0 on ( !( Suction and Bipolar ) )
				me->_policy_p1_state = POLICY_STATE_surgical_policy_p1_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Suction && inputs->Bipolar) {
				//transition s0 -> violation on ( Suction and Bipolar )
				me->_policy_p1_state = POLICY_STATE_surgical_policy_p1_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "surgical_policy_p1_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p1_state != POLICY_STATE_surgical_policy_p1_violation);
}

//OUTPUT POLICY p1 END

//OUTPUT POLICY p2_dissecting_time BEGIN
//This will run the input enforcer for surgical_policy's policy p2_dissecting_time
void surgical_policy_run_output_enforcer_p2_dissecting_time(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p2_dissecting_time_state) {
		case POLICY_STATE_surgical_policy_p2_dissecting_time_s0:
			
			if(inputs->Dissecting && inputs->CONSEC_Dissecting > CONST_p2_dissecting_time_MAX_Dissecting) {
				//transition s0 -> violation on ( Dissecting and ( CONSEC_Dissecting > MAX_Dissecting ) )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p2_dissecting_time_state) {
		case POLICY_STATE_surgical_policy_p2_dissecting_time_s0:
			
			if( !(inputs->Dissecting)) {
				//transition s0 -> s0 on ( !Dissecting )
				me->_policy_p2_dissecting_time_state = POLICY_STATE_surgical_policy_p2_dissecting_time_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Dissecting && inputs->CONSEC_Dissecting <= CONST_p2_dissecting_time_MAX_Dissecting) {
				//transition s0 -> s0 on ( Dissecting and ( CONSEC_Dissecting <= MAX_Dissecting ) )
				me->_policy_p2_dissecting_time_state = POLICY_STATE_surgical_policy_p2_dissecting_time_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Dissecting && inputs->CONSEC_Dissecting > CONST_p2_dissecting_time_MAX_Dissecting) {
				//transition s0 -> violation on ( Dissecting and ( CONSEC_Dissecting > MAX_Dissecting ) )
				me->_policy_p2_dissecting_time_state = POLICY_STATE_surgical_policy_p2_dissecting_time_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "surgical_policy_p2_dissecting_time_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p2_dissecting_time_state != POLICY_STATE_surgical_policy_p2_dissecting_time_violation);
}

//OUTPUT POLICY p2_dissecting_time END

//OUTPUT POLICY p3_total_suction BEGIN
//This will run the input enforcer for surgical_policy's policy p3_total_suction
void surgical_policy_run_output_enforcer_p3_total_suction(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p3_total_suction_state) {
		case POLICY_STATE_surgical_policy_p3_total_suction_s0:
			
			if(inputs->Suction && inputs->TOTAL_Suction > CONST_p3_total_suction_MAX_TOTAL_Suction) {
				//transition s0 -> violation on ( Suction and ( TOTAL_Suction > MAX_TOTAL_Suction ) )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p3_total_suction_state) {
		case POLICY_STATE_surgical_policy_p3_total_suction_s0:
			
			if( !(inputs->Suction)) {
				//transition s0 -> s0 on ( !Suction )
				me->_policy_p3_total_suction_state = POLICY_STATE_surgical_policy_p3_total_suction_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Suction && inputs->TOTAL_Suction <= CONST_p3_total_suction_MAX_TOTAL_Suction) {
				//transition s0 -> s0 on ( Suction and ( TOTAL_Suction <= MAX_TOTAL_Suction ) )
				me->_policy_p3_total_suction_state = POLICY_STATE_surgical_policy_p3_total_suction_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Suction && inputs->TOTAL_Suction > CONST_p3_total_suction_MAX_TOTAL_Suction) {
				//transition s0 -> violation on ( Suction and ( TOTAL_Suction > MAX_TOTAL_Suction ) )
				me->_policy_p3_total_suction_state = POLICY_STATE_surgical_policy_p3_total_suction_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "surgical_policy_p3_total_suction_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p3_total_suction_state != POLICY_STATE_surgical_policy_p3_total_suction_violation);
}

//OUTPUT POLICY p3_total_suction END

//OUTPUT POLICY p4_cooldown_dissecting BEGIN
//This will run the input enforcer for surgical_policy's policy p4_cooldown_dissecting
void surgical_policy_run_output_enforcer_p4_cooldown_dissecting(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p4_cooldown_dissecting_state) {
		case POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0:
			
			if(inputs->Dissecting && inputs->IN_COOLDOWN_Dissecting) {
				//transition s0 -> violation on ( Dissecting and IN_COOLDOWN_Dissecting )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p4_cooldown_dissecting_state) {
		case POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0:
			
			if( !(inputs->Dissecting)) {
				//transition s0 -> s0 on ( !Dissecting )
				me->_policy_p4_cooldown_dissecting_state = POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Dissecting && !(inputs->IN_COOLDOWN_Dissecting)) {
				//transition s0 -> s0 on ( Dissecting and !IN_COOLDOWN_Dissecting )
				me->_policy_p4_cooldown_dissecting_state = POLICY_STATE_surgical_policy_p4_cooldown_dissecting_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Dissecting && inputs->IN_COOLDOWN_Dissecting) {
				//transition s0 -> violation on ( Dissecting and IN_COOLDOWN_Dissecting )
				me->_policy_p4_cooldown_dissecting_state = POLICY_STATE_surgical_policy_p4_cooldown_dissecting_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "surgical_policy_p4_cooldown_dissecting_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p4_cooldown_dissecting_state != POLICY_STATE_surgical_policy_p4_cooldown_dissecting_violation);
}

//OUTPUT POLICY p4_cooldown_dissecting END

//OUTPUT POLICY p5_precedence_cusa BEGIN
//This will run the input enforcer for surgical_policy's policy p5_precedence_cusa
void surgical_policy_run_output_enforcer_p5_precedence_cusa(enforcervars_surgical_policy_t* me, inputs_surgical_policy_t* inputs, outputs_surgical_policy_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_p5_precedence_cusa_state) {
		case POLICY_STATE_surgical_policy_p5_precedence_cusa_s0:
			
			if(inputs->Cusa && !(inputs->Dissecting_Ever_Used)) {
				//transition s0 -> violation on ( Cusa and !Dissecting_Ever_Used )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_p5_precedence_cusa_state) {
		case POLICY_STATE_surgical_policy_p5_precedence_cusa_s0:
			
			if( !(inputs->Cusa)) {
				//transition s0 -> s0 on ( !Cusa )
				me->_policy_p5_precedence_cusa_state = POLICY_STATE_surgical_policy_p5_precedence_cusa_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Cusa && inputs->Dissecting_Ever_Used) {
				//transition s0 -> s0 on ( Cusa and Dissecting_Ever_Used )
				me->_policy_p5_precedence_cusa_state = POLICY_STATE_surgical_policy_p5_precedence_cusa_s0;
				//set expressions
				
				break;
			} 
			if(inputs->Cusa && !(inputs->Dissecting_Ever_Used)) {
				//transition s0 -> violation on ( Cusa and !Dissecting_Ever_Used )
				me->_policy_p5_precedence_cusa_state = POLICY_STATE_surgical_policy_p5_precedence_cusa_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "surgical_policy_p5_precedence_cusa_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_p5_precedence_cusa_state != POLICY_STATE_surgical_policy_p5_precedence_cusa_violation);
}

//OUTPUT POLICY p5_precedence_cusa END



//This function is provided in "F_surgical_policy.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

