import pickle

# Load the processed detections generated by your Colab script
DETECTION_FILE = "preds_video.pckl"

with open(DETECTION_FILE, 'rb') as f:
    # last_video is the total frame count, preds_video is the dictionary
    last_video, preds_video = pickle.load(f)

# --- Persistent state across calls ---
# Index mapping: 0=Suction(idx1), 1=Bipolar(idx2), 2=Dissecting(idx4), 3=Cusa(idx5)

consec_counts = [0, 0, 0, 0]       # Consecutive frames ON
consec_off    = [0, 0, 0, 0]       # Consecutive frames OFF
total_active  = [0, 0, 0, 0]       # Cumulative total usage (all frames)
prev_state    = [0, 0, 0, 0]       # Tool state in previous frame (0=off, 1=on)
dissecting_ever_used = 0            # Whether Dissecting has been active in any frame
in_cooldown_state = 0               # Sticky flag: ON after 5 ON frames, OFF after 5 OFF frames

def test_frame(idx):
    """
    Called by main.c. Converts frame-wise detections into a binary vector
    plus all tracking counters for the FSM policies.

    Label mapping:
      0 -> Background
      1 -> Suction
      2 -> Bipolar Forceps
      3 -> Other
      4 -> Dissecting Forceps
      5 -> Cusa

    Returns: [Background, Suction, Bipolar, Other, Dissecting, Cusa,
              consec_suction, consec_bipolar, consec_dissecting, consec_cusa,
              consec_off_suction, consec_off_bipolar, consec_off_dissecting, consec_off_cusa,
              total_suction,
              in_cooldown_dissecting,
              dissecting_ever_used]
    """
    global consec_counts, consec_off, total_active
    global prev_state, dissecting_ever_used, in_cooldown_state

    frame_id = idx + 1

    # Initialize presence vector for 6 possible classes
    presence_vector = [0] * 6

    if frame_id in preds_video:
        for det in preds_video[frame_id]:
            scores = det['scores']
            for i in range(len(scores)):
                if scores[i] == 1:
                    presence_vector[i] = 1

    # --- Update all tracking counters ---
    # Skip index 3 (Other) — only track Suction(1), Bipolar(2), Dissecting(4), Cusa(5)
    tool_indices = [1, 2, 4, 5]  # indices into presence_vector

    for k, tool_idx in enumerate(tool_indices):
        if presence_vector[tool_idx] == 1:
            # Tool is ON this frame
            total_active[k] += 1
            consec_counts[k] += 1
            consec_off[k] = 0
        else:
            # Tool is OFF this frame
            if k == 2 and prev_state[k] == 1 and consec_counts[k] >= 5:
                # Transition ON -> OFF after a 5+ streak: Trigger cooldown for Dissecting
                in_cooldown_state = 1
            
            consec_off[k] += 1
            consec_counts[k] = 0

        prev_state[k] = presence_vector[tool_idx]

    # --- Check if Dissecting (k=2) has ever been used ---
    if presence_vector[tool_indices[2]] == 1:
        dissecting_ever_used = 1

    # --- Reset sticky cooldown flag for Dissecting (k=2) ---
    if consec_off[2] >= 5:
        in_cooldown_state = 0

    # Return extended vector
    return (presence_vector
            + list(consec_counts)                       # indices 6-9
            + list(consec_off)                          # indices 10-13
            + [total_active[0]]                         # index 14: total Suction
            + [in_cooldown_state]                       # index 15: cooldown flag
            + [dissecting_ever_used])                   # index 16: precedence flag